// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUOgdnoYAJxybuTCX8_2ha0_1Rwhz2QMs',
    appId: '1:990764002293:web:94f5f12e7b43b9484b0ebc',
    messagingSenderId: '990764002293',
    projectId: 'chefup-256',
    authDomain: 'chefup-256.firebaseapp.com',
    storageBucket: 'chefup-256.firebasestorage.app',
    measurementId: 'G-RZ8ZHRRXVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJRt8-V8mBUEr-T00XaaVCv-Au4QZEoA0',
    appId: '1:990764002293:android:69d7e527d8c5b5284b0ebc',
    messagingSenderId: '990764002293',
    projectId: 'chefup-256',
    storageBucket: 'chefup-256.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1STYubp8zJG7wGPYWuEG2QTkcng2HZ34',
    appId: '1:990764002293:ios:314c180f2d4ed3384b0ebc',
    messagingSenderId: '990764002293',
    projectId: 'chefup-256',
    storageBucket: 'chefup-256.firebasestorage.app',
    iosBundleId: 'com.example.atividadeAula10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1STYubp8zJG7wGPYWuEG2QTkcng2HZ34',
    appId: '1:990764002293:ios:314c180f2d4ed3384b0ebc',
    messagingSenderId: '990764002293',
    projectId: 'chefup-256',
    storageBucket: 'chefup-256.firebasestorage.app',
    iosBundleId: 'com.example.atividadeAula10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUOgdnoYAJxybuTCX8_2ha0_1Rwhz2QMs',
    appId: '1:990764002293:web:15617d946c3619d04b0ebc',
    messagingSenderId: '990764002293',
    projectId: 'chefup-256',
    authDomain: 'chefup-256.firebaseapp.com',
    storageBucket: 'chefup-256.firebasestorage.app',
    measurementId: 'G-NKK4VQ1X5L',
  );
}
